### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [loverus/lab_TRPO#3]
Go ahead and implement task 2

**Comment by SemenMartynov** [comment]
Checked

**Comment by mariiamanuylova** [comment]
Task 2 was completed. The code is in the repository.

![image](https://user-images.githubusercontent.com/22224425/35356312-11218ce0-0161-11e8-8c1a-c44bdc11794d.png)

**Comment by SemenMartynov** [comment]
Ok, I can build but I don't know how to run this image.
Please update and format your documentation.

**Comment by mariiamanuylova** [comment]
Documentation has been updated.

**Comment by SemenMartynov** [comment]
`Error: Unable to access jarfile /build/libs/getjsonformat.jar`
Did you try to run you project before submitting?

**Comment by mariiamanuylova** [comment]
I did not have any errors. I checked again, cloning the repository, there are no errors.

![image](https://user-images.githubusercontent.com/22224425/35472861-1f87601a-0388-11e8-9e2f-d97ddab40e66.png)

**Comment by SemenMartynov** [comment]
Yes, but try to execute client's request now...

**Comment by mariiamanuylova** [comment]
I understood. Error corrected. Now it works.

https://github.com/loverus/lab_TRPO/commit/4d310c3364616dccc388303c37dc3bd039b9e2b1

**Comment by SemenMartynov** [comment]
Please, follow git-flow for your commits, as we discuses on the seminars.
